name: xpk
description: "Explore the pakistan"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # ======================= packages start here =============================
  
  #%%%%%%%%%%%%%%%%%%%%%%%%%%%%% utiles %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_otp_text_field:
  file_picker: ^8.3.7
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  lottie: ^3.3.1
  intl: ^0.20.2
  easy_stepper: ^0.8.5+1
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.2.1

  #%%%%%%%%%%%%%%%%%%%%%%%%%%%%% state management %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  get: ^4.6.6

  #%%%%%%%%%%%%%%%%%%%%%%%%%%%%% network %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  http: ^1.3.0
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  #connectivity_plus: ^6.1.3


  #%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Google Map %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.3
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.1.0
  google_places_flutter: ^2.1.0
  #flutter_google_places_sdk: ^0.4.0

  #%%%%%%%%%%%%%%%%%%%%%%%%%%%%% FireBase %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_app_check: ^0.3.2+4
 
  


  # ===================packages end here=============







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/xpk-icon.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#ffffff" 
  adaptive_icon_foreground: "assets/logo/xpk-icon.png" 
  web:
    generate: true
    image_path: "assets/logo/xpk-icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/xpk-icon.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/logo/xpk-icon.png"


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/Animation/
    - assets/images/
    - assets/svg_image/
